/**
 * "You asked" prompt extraction — the Overview line must show the OPERATOR's last prompt,
 * never a harness-injected user turn. Claude Code writes several role:"user" turns that the
 * operator never typed (the isMeta "Continue from where you left off." resume banner, slash-command
 * expansions, standalone <system-reminder> blocks, local-command stdout). Before the fix those
 * could win the "last user prompt" scan, so "You asked" showed injected noise or — when a pure
 * envelope got stripped to empty by the renderer — blanked out entirely.
 *
 * Standalone ring (run via run_all.ts). Exits non-zero on any failure.
 */
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { parseTranscript, parseTranscriptTail, findLastUserPromptDeep, operatorPromptText } from "../core/transcript";

let failures = 0;
function check(name: string, cond: boolean, detail = "") {
  if (cond) console.log(`  \x1b[32m✓\x1b[0m ${name}`);
  else { failures++; console.log(`  \x1b[31m✗ ${name}\x1b[0m${detail ? `  — ${detail}` : ""}`); }
}

/** Build a transcript file from raw line objects (full control over isMeta / string vs array
 *  content), so we can reproduce the exact injected-turn shapes Claude Code writes. */
type Line = { type: "user" | "assistant"; content: any; isMeta?: boolean };
function writeRaw(lines: Line[]): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "cos-prompt-"));
  const file = path.join(dir, "session.jsonl");
  const out = [JSON.stringify({ type: "mode", timestamp: "2026-06-09T12:00:00.000Z" })];
  let t = Date.parse("2026-06-09T12:00:01.000Z");
  for (const l of lines) {
    const o: any = { type: l.type, timestamp: new Date(t).toISOString(), cwd: "/x",
      message: { role: l.type, stop_reason: l.type === "assistant" ? "end_turn" : null, content: l.content } };
    if (l.isMeta) o.isMeta = true;
    out.push(JSON.stringify(o));
    t += 1000;
  }
  fs.writeFileSync(file, out.join("\n") + "\n");
  return file;
}
const txt = (s: string) => [{ type: "text", text: s }];
const toolResult = (s: string) => [{ type: "tool_result", tool_use_id: "t1", content: s }];

console.log("\n== operatorPromptText: strips injected envelopes, keeps real prose ==");
check("pure <system-reminder> -> empty", operatorPromptText("<system-reminder>you are great</system-reminder>") === "");
check("slash-command expansion -> empty",
  operatorPromptText("<command-name>/clear</command-name>\n  <command-message>clear</command-message>") === "");
check("local-command stdout -> empty",
  operatorPromptText("<local-command-stdout>build ok</local-command-stdout>") === "");
check("Caveat resume banner -> empty",
  operatorPromptText("Caveat: The messages below were generated by the user while running local commands.\n\n") === "");
check("real prompt -> unchanged", operatorPromptText("fix the importer crash") === "fix the importer crash");
check("real prompt with a reminder appended -> keeps the real text",
  operatorPromptText("fix the importer crash\n<system-reminder>some injected context</system-reminder>") === "fix the importer crash");
check("whitespace-only -> empty", operatorPromptText("   \n  ") === "");

console.log("\n== parseTranscript().lastUserPrompt: skips injected user turns ==");
{
  // The exact case from this very session: real prompt, then Claude works, then the harness
  // injects the isMeta resume banner as the most-recent user turn.
  const f = writeRaw([
    { type: "user", content: txt("speed up the 8-GPU training run") },
    { type: "assistant", content: txt("Looking into it…") },
    { type: "user", content: txt("Continue from where you left off."), isMeta: true },
    { type: "assistant", content: txt("Resuming.") },
  ]);
  const v = parseTranscript(f);
  check("skips the isMeta 'Continue…' banner -> picks the real prompt",
    v.lastUserPrompt?.text === "speed up the 8-GPU training run", `got: ${JSON.stringify(v.lastUserPrompt?.text)}`);
}
{
  // A standalone <system-reminder> as the latest user turn (string content) used to blank the card.
  const f = writeRaw([
    { type: "user", content: txt("de-dup the duplicate user records") },
    { type: "assistant", content: txt("On it.") },
    { type: "user", content: "<system-reminder>The task tools haven't been used recently.</system-reminder>" },
  ]);
  const v = parseTranscript(f);
  check("skips a standalone <system-reminder> turn -> picks the real prompt",
    v.lastUserPrompt?.text === "de-dup the duplicate user records", `got: ${JSON.stringify(v.lastUserPrompt?.text)}`);
}
{
  // A slash-command expansion as the latest user turn.
  const f = writeRaw([
    { type: "user", content: txt("how is inference going?") },
    { type: "assistant", content: txt("All green.") },
    { type: "user", content: txt("<command-name>/gpubox</command-name>\n  <command-message>gpubox</command-message>") },
  ]);
  const v = parseTranscript(f);
  check("skips a /slash-command expansion turn -> picks the real prompt",
    v.lastUserPrompt?.text === "how is inference going?", `got: ${JSON.stringify(v.lastUserPrompt?.text)}`);
}
{
  // Existing behavior preserved: a tool_result continuation never counts as the operator's prompt.
  const f = writeRaw([
    { type: "user", content: txt("run the tests") },
    { type: "assistant", content: txt("Running…") },
    { type: "user", content: toolResult("47 passed") },
  ]);
  const v = parseTranscript(f);
  check("still skips tool_result continuations -> picks the real prompt",
    v.lastUserPrompt?.text === "run the tests", `got: ${JSON.stringify(v.lastUserPrompt?.text)}`);
}
{
  // A short, ordinary prompt (e.g. "continue") is real and must be kept verbatim.
  const f = writeRaw([{ type: "user", content: txt("continue") }, { type: "assistant", content: txt("ok") }]);
  const v = parseTranscript(f);
  check("a short real prompt ('continue') is kept", v.lastUserPrompt?.text === "continue", `got: ${JSON.stringify(v.lastUserPrompt?.text)}`);
}

(async () => {
  console.log("\n== deep recovery: latest prompt past the 128KB tail (the 'You asked went stale' bug) ==");
  // The operator asks TWO things; between the LATEST prompt and Claude's final answer there is
  // >128KB of tool-call work, so the latest prompt scrolls out of the hot 128KB tail. The tail
  // reader then returns null for lastUserPrompt — engine.surface() USED TO fall back to a PREVIOUS
  // item's stored prompt (the OLD turn) → the Overview "You asked" line showed a stale, earlier
  // request. The fix: surface() now deep-scans to recover the TRUE latest prompt (and never reuses
  // a different turn's prompt). This pins the recovery primitive: deep scan returns the SECOND
  // (latest) prompt, never the first.
  const bulk = "x".repeat(2000);
  const toolWork: Line[] = [];
  for (let i = 0; i < 80; i++) {
    toolWork.push({ type: "assistant", content: [{ type: "tool_use", id: "t" + i, name: "Bash", input: {} }] });
    toolWork.push({ type: "user", content: toolResult(`tool output ${i}: ${bulk}`) });
  }
  const f = writeRaw([
    { type: "user", content: txt("OLD prompt — summarize the inference logs") },
    { type: "assistant", content: txt("Done summarizing.") },
    { type: "user", content: txt("LATEST prompt — now fix the importer crash") },
    ...toolWork,
    { type: "assistant", content: txt("Fixed it; tests pass.") },
  ]);
  const st = fs.statSync(f);
  const tail = await parseTranscriptTail(f, st.mtimeMs);
  check("the 128KB tail no longer holds the operator's latest prompt (precondition of the bug)",
    !tail.lastUserPrompt || !/LATEST prompt/.test(tail.lastUserPrompt.text),
    `got: ${JSON.stringify(tail.lastUserPrompt?.text)}`);
  const deep = await findLastUserPromptDeep(f);
  check("deep scan recovers the LATEST prompt", /LATEST prompt/.test(deep), `got: ${JSON.stringify(deep)}`);
  check("deep scan does NOT return the stale earlier prompt", !/OLD prompt/.test(deep), `got: ${JSON.stringify(deep)}`);

  console.log(failures === 0
    ? "\n\x1b[32m  transcript-prompt: ALL GREEN\x1b[0m\n"
    : `\n\x1b[31m  transcript-prompt: ${failures} FAILED\x1b[0m\n`);
  process.exit(failures === 0 ? 0 : 1);
})();
