/** Preload: expose a minimal, safe IPC surface to the renderer. */
import { contextBridge, ipcRenderer } from "electron";

contextBridge.exposeInMainWorld("cockpit", {
  state: () => ipcRenderer.invoke("state"),
  tick: () => ipcRenderer.invoke("tick"),
  sendAnswer: (itemId: number, answer?: string) => ipcRenderer.invoke("sendAnswer", itemId, answer),
  ack: (itemId: number) => ipcRenderer.invoke("ack", itemId),
  snooze: (itemId: number, minutes?: number) => ipcRenderer.invoke("snooze", itemId, minutes),
  feedback: (itemId: number, fb: string) => ipcRenderer.invoke("feedback", itemId, fb),
  rawTranscript: (itemId: number) => ipcRenderer.invoke("rawTranscript", itemId),
  prettyTranscript: (itemId: number) => ipcRenderer.invoke("prettyTranscript", itemId),
  attachCommand: (sessionId: number) => ipcRenderer.invoke("attachCommand", sessionId),
  openTerminal: (sessionId: number) => ipcRenderer.invoke("openTerminal", sessionId),
  pane: (sessionId: number, lines?: number) => ipcRenderer.invoke("pane", sessionId, lines),
  sendPaneKey: (sessionId: number, key: string, named?: boolean) => ipcRenderer.invoke("sendPaneKey", sessionId, key, named),
  setPinned: (sessionId: number, pinned: boolean) => ipcRenderer.invoke("setPinned", sessionId, pinned),
  setManualImportance: (sessionId: number, value: number | null) => ipcRenderer.invoke("setManualImportance", sessionId, value),
  renameSession: (sessionId: number, title: string) => ipcRenderer.invoke("renameSession", sessionId, title),
  prDiff: (sessionId: number) => ipcRenderer.invoke("prDiff", sessionId),
  launchSession: (repo: string, title: string, prompt: string) => ipcRenderer.invoke("launchSession", repo, title, prompt),
  newSession: (kind: string, prompt?: string, importance?: number | null) => ipcRenderer.invoke("newSession", kind, prompt, importance),
  complete: (sessionId: number) => ipcRenderer.invoke("complete", sessionId),
  activate: (sessionId: number) => ipcRenderer.invoke("activate", sessionId),
  reasonFeedback: (itemId: number, direction: string, reason: string) => ipcRenderer.invoke("reasonFeedback", itemId, direction, reason),
  resurfaceAll: () => ipcRenderer.invoke("resurfaceAll"),
  sessionPr: (sessionId: number) => ipcRenderer.invoke("sessionPr", sessionId),
  mergePr: (sessionId: number, deleteBranch?: boolean) => ipcRenderer.invoke("mergePr", sessionId, !!deleteBranch),
  diag: (payload: any) => ipcRenderer.invoke("diag", payload),
  takeOverable: () => ipcRenderer.invoke("takeOverable"),
  takeOver: (sessionId: number, confirmedBusy?: boolean) => ipcRenderer.invoke("takeOver", sessionId, !!confirmedBusy),
  takeOverAll: (confirmedBusy?: boolean) => ipcRenderer.invoke("takeOverAll", !!confirmedBusy),
  worktreeDiff: (sessionId: number) => ipcRenderer.invoke("worktreeDiff", sessionId),
  prReviews: (sessionId: number) => ipcRenderer.invoke("prReviews", sessionId),
  diffViewed: (sessionId: number) => ipcRenderer.invoke("diffViewed", sessionId),
  setDiffViewed: (sessionId: number, filePath: string, viewed: boolean) => ipcRenderer.invoke("setDiffViewed", sessionId, filePath, viewed),
  prStatus: (sessionId: number) => ipcRenderer.invoke("prStatus", sessionId),
  prMerge: (sessionId: number, method?: string, deleteBranch?: boolean) => ipcRenderer.invoke("prMerge", sessionId, method, !!deleteBranch),
  kanbanStart: (sessionId: number) => ipcRenderer.invoke("kanbanStart", sessionId),
  kanbanAnswer: (sessionId: number, answers: string[]) => ipcRenderer.invoke("kanbanAnswer", sessionId, answers),
  kanbanAppend: (sessionId: number) => ipcRenderer.invoke("kanbanAppend", sessionId),
  undo: () => ipcRenderer.invoke("undo"),
  setFocus: (focus: string) => ipcRenderer.invoke("setFocus", focus),
  keymap: () => ipcRenderer.invoke("keymap"),
  reloadConfig: () => ipcRenderer.invoke("reloadConfig"),
  onUpdate: (cb: () => void) => ipcRenderer.on("update", cb),
});
