/**
 * FIX O/EE: per-session HTML visualizations. Two sources, merged + deduped by absolute path:
 *   1. The `/visualize` convention dir `<viz_dir>/<task-slug>/*.html`.
 *   2. FIX EE/EE2: ANY `.html` the session itself PRODUCED — detected from its transcript:
 *      Write/Edit tool calls with a *.html file_path, plus .html paths mentioned in Bash
 *      commands/results/prose (mtime-gated to the session's lifetime). So whenever a session
 *      produces HTML (any way, incl. a Bash-run script), it shows in the HTML view automatically.
 * Files are served by `/api/viz`, containment-guarded to viz_dir OR the session's worktree.
 */
import * as fs from "fs";
import * as path from "path";

export interface VizFile { name: string; file: string; mtime: number } // file = basename (display); served by index; mtime drives newest-first order + the tab age label
interface VizEntry { name: string; file: string; abs: string; mtime: number }

export function vizSlug(s: string): string {
  return (s || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

function candidateSlugs(session: any): string[] {
  const out = new Set<string>();
  for (const v of [session?.clean_title, session?.title]) { const s = vizSlug(v || ""); if (s) out.add(s); }
  const branch = String(session?.branch || "");
  const base = branch.replace(/^.*\//, "").replace(/^cockpit-/, "");
  const bs = vizSlug(base); if (bs) out.add(bs);
  return [...out];
}

function folderMatches(dir: string, slugs: string[]): boolean {
  const d = vizSlug(dir);
  if (!d) return false;
  for (const s of slugs) {
    if (!s) continue;
    if (d === s) return true;
    if (s.length >= 6 && (d.includes(s) || s.includes(d))) return true;
  }
  return false;
}

/** The `/visualize` convention folder's html files (abs paths), or []. */
function conventionEntries(vizDir: string, session: any): VizEntry[] {
  if (!vizDir || !session) return [];
  let dirs: string[] = []; try { dirs = fs.readdirSync(vizDir); } catch { return []; }
  const slugs = candidateSlugs(session);
  if (!slugs.length) return [];
  let chosen: string | null = null;
  for (const dir of dirs) {
    let isDir = false; try { isDir = fs.statSync(path.join(vizDir, dir)).isDirectory(); } catch {}
    if (!isDir) continue;
    if (slugs.includes(vizSlug(dir))) { chosen = dir; break; }
    if (!chosen && folderMatches(dir, slugs)) chosen = dir;
  }
  if (!chosen) return [];
  const folder = path.join(vizDir, chosen);
  let files: string[] = []; try { files = fs.readdirSync(folder).filter((f) => /\.html?$/i.test(f)); } catch { return []; }
  // mtime is recomputed by vizEntries.add() (the authoritative sort key) — 0 here is just a placeholder.
  return files.map((f) => ({ name: f.replace(/\.html?$/i, ""), file: f, abs: path.resolve(folder, f), mtime: 0 }));
}

// FIX EE2: incremental whole-transcript scan. The old version tail-read only the LAST 256KB and
// only matched Write/Edit file_path keys — so html generated by a Bash-run script (e.g.
// `python gen.py -o scripts/unified_eval/spectrograms.html`, no Write tool call) or written early
// in a long session was invisible (the "task made an html but the HTML view doesn't show it" bug).
// Transcripts are append-only JSONL: keep a per-transcript scan offset and read ONLY the newly
// appended bytes each call (bounded per call so a 20MB transcript never blocks a tick; a small
// overlap re-scan catches a token split across reads). Two detection tiers:
//   - explicit: Write/Edit/NotebookEdit tool-call paths (tool-name-bound — a Read of someone
//     else's html does NOT count) → listed whenever the file exists.
//   - mentioned: any path-looking token ending in .htm(l) anywhere in the transcript (Bash
//     commands, tool results, assistant prose). Mentions come from semi-untrusted text, so they
//     are triple-gated: (a) the file exists AND its mtime is >= the session's start (transcript
//     birthtime), so html the session merely TALKED ABOUT (vendored index.html, old reports)
//     doesn't become a noise tab; (b) the resolved path must sit under the session worktree,
//     viz_dir, or a configured mention root (cfg.viz_mention_roots) — never arbitrary fs; (c) no
//     hidden path component (blocks ~/.ssh/… style mentions).
const SCAN_MAX_PER_CALL = 4 * 1024 * 1024;
const SCAN_OVERLAP = 64 * 1024;
const SCAN_MAX_MENTIONS = 64; // bounded set — at cap, dead entries are swept, then oldest evicted
const SCAN_MAX_EXPLICIT = 128;
const SCAN_BORN_SLACK_MS = 2_000; // fs-timestamp granularity only — a cockpit worktree is checked
// out seconds before the session starts, so a bigger slack would let every vendored repo html in.
interface ScanState { next: number; born: number; warned: boolean; lastUse: number; explicit: Set<string>; mentioned: Set<string> }
const _scan = new Map<string, ScanState>();

function resolveHtmlPath(raw: string, worktree: string): string | null {
  let p = raw.replace(/\\(.)/g, "$1");
  if (p.startsWith("~/")) p = path.join(process.env.HOME || "", p.slice(2));
  if (!path.isAbsolute(p)) { if (!worktree) return null; p = path.resolve(worktree, p); }
  return path.resolve(p);
}

const hasHiddenComponent = (p: string) => /(^|\/)\.[^/]/.test(p);
/** The containment root containing `p`, or null. Roots are operator-trusted (worktree, viz_dir,
 *  configured mention roots) — the hidden-component check must run on the path RELATIVE to the
 *  matched root, never the full path: cockpit worktrees live under `.cockpit-worktrees/…`, so a
 *  full-path check would reject every mention inside the session's own worktree. */
function matchRoot(p: string, roots: string[]): string | null {
  for (const r of roots) {
    if (!r) continue;
    const rr = r.endsWith(path.sep) ? r.slice(0, -path.sep.length) : r;
    if (p === rr || p.startsWith(rr + path.sep)) return rr;
  }
  return null;
}

/** Bounded-set add. At the cap: sweep dead entries (gone, or never-displayable per `dead`) at
 *  most ONCE per scan call — a per-insert sweep is O(cap) statSyncs and a mention flood would
 *  freeze the tick — then FIFO-evict the oldest. Junk can never permanently disable detection,
 *  and never-displayable junk can't crowd a currently-displayed tab out. */
function addBounded(set: Set<string>, p: string, cap: number, dead: (q: string) => boolean, swept: { v: boolean }) {
  if (set.has(p)) return;
  if (set.size >= cap) {
    if (!swept.v) { swept.v = true; for (const q of [...set]) if (dead(q)) set.delete(q); }
    while (set.size >= cap) { const oldest = set.values().next().value as string | undefined; if (oldest === undefined) break; set.delete(oldest); }
  }
  set.add(p);
}

// token chars for a mentioned path: [A-Za-z0-9_.@+~/-] — excludes quote/backslash/space so
// JSON-escaped string boundaries terminate the token.
function isTokChar(c: number): boolean {
  return (c >= 48 && c <= 57) || (c >= 65 && c <= 90) || (c >= 97 && c <= 122) ||
    c === 95 /*_*/ || c === 46 /*.*/ || c === 64 /*@*/ || c === 43 /*+*/ || c === 126 /*~*/ || c === 45 /*-*/ || c === 47 /*/*/;
}

// LENGTH-PRESERVING case fold — String#toLowerCase can change the length (U+0130 → 2 code
// units), which would de-sync `lower` indexes from `chunk` and drop every later detection.
// Native toLowerCase is ~90x faster than a regex fold on 4MB chunks, so use it whenever it
// preserved the length (no lowercase mapping shrinks, so equal length ⟹ 1:1 ⟹ indexes aligned).
const asciiLower = (s: string) => {
  const l = s.toLowerCase();
  return l.length === s.length ? l : s.replace(/[A-Z]/g, (c) => String.fromCharCode(c.charCodeAt(0) | 32));
};

/** Linear .htm(l)-mention scanner. An unanchored regex here is quadratic on long word-char runs
 *  (base64 screenshot blobs in transcripts → measured 13s+/100KB, would freeze the tick), so:
 *  indexOf(".htm") for candidate sites, then a bounded backwards charcode walk for the token. */
function scanHtmlMentions(chunk: string, cb: (token: string) => void): void {
  const lower = asciiLower(chunk);
  let i = 0;
  while ((i = lower.indexOf(".htm", i)) !== -1) {
    let end = i + 4;
    if (lower.charCodeAt(end) === 108 /*l*/) end++;
    if (end < chunk.length && isTokChar(chunk.charCodeAt(end))) { i = end; continue; } // .htmx/.html5/…
    let s = i, steps = 0;
    while (s > 0 && steps < 512 && isTokChar(chunk.charCodeAt(s - 1))) { s--; steps++; }
    if (steps > 0 && steps < 512) cb(chunk.slice(s, end));
    i = end;
  }
}

/** FIX EE/EE2: html files the session produced, from its transcript (see the block comment).
 *  `mentionRoots` = the containment roots for the mentioned tier (worktree/viz_dir always added). */
function transcriptHtml(transcriptPath: string | null, worktree: string, mentionRoots: string[]): string[] {
  if (!transcriptPath) return [];
  let st: fs.Stats; try { st = fs.statSync(transcriptPath); } catch { return []; }
  let sc = _scan.get(transcriptPath);
  if (!sc || st.size < sc.next) {
    // born is fixed at first sight: a live ctime/mtime fallback would MOVE with every append on
    // birthtime-less filesystems and silently expel tabs mid-session.
    const born = (st.birthtimeMs > 0 ? st.birthtimeMs : Math.min(st.ctimeMs || Infinity, st.mtimeMs || Infinity, Date.now())) - SCAN_BORN_SLACK_MS;
    sc = { next: 0, born, warned: false, lastUse: 0, explicit: new Set(), mentioned: new Set() };
    _scan.set(transcriptPath, sc);
    if (_scan.size > 300) { // prune scan state for transcripts not asked about in 30min
      const cut = Date.now() - 30 * 60_000;
      for (const [k, v] of _scan) if (v !== sc && v.lastUse < cut) _scan.delete(k);
    }
  }
  sc.lastUse = Date.now();
  // resolve the containment roots BEFORE the read advances the cursor — a throw here (e.g. a
  // junk config root) must not consume transcript bytes whose mention scan never ran.
  const roots = [worktree, ...mentionRoots].filter((r) => typeof r === "string" && r).map((r) => path.resolve(r));
  if (st.size > sc.next) {
    const start = Math.max(0, sc.next - SCAN_OVERLAP);
    const len = Math.min(st.size - start, SCAN_MAX_PER_CALL); // catch-up continues next call
    let chunk = "";
    try {
      const fd = fs.openSync(transcriptPath, "r");
      let n = 0;
      try { const buf = Buffer.alloc(len); n = fs.readSync(fd, buf, 0, len, start); chunk = buf.toString("utf8", 0, n); }
      finally { fs.closeSync(fd); }
      sc.next = start + n;
      sc.warned = false; // a later persistent failure gets its own warning
    } catch (e) {
      // transient errors retry next call (offset untouched) — but say so ONCE if it persists
      if (!sc.warned) { sc.warned = true; console.warn(`viz: transcript scan failed for ${transcriptPath}: ${String(e)}`); }
    }
    // explicit: ONLY write-tool calls count as "the session produced this" — tool_use lines
    // serialize "name" before "input", so bind the key to the tool name on the same line. The
    // tempered window (?:(?!"name"…)…) stops at the NEXT tool block, so a parallel Read's
    // file_path on the same line can't ride in on a preceding Write/Edit.
    const keyRe = /"name"\s*:\s*"(?:Write|Edit|NotebookEdit)"(?:(?!"name"\s*:)[^\n]){0,256}?"(?:file_path|notebook_path)"\s*:\s*"((?:[^"\\]|\\.)+?\.html?)"/gi;
    let m: RegExpExecArray | null;
    const sweptE = { v: false }, sweptM = { v: false };
    const deadExplicit = (q: string) => { try { return !fs.statSync(q).isFile(); } catch { return true; } };
    const deadMention = (q: string) => { try { const f = fs.statSync(q); return !f.isFile() || f.mtimeMs < sc!.born; } catch { return true; } };
    while ((m = keyRe.exec(chunk))) { const r = resolveHtmlPath(m[1], worktree); if (r) addBounded(sc.explicit, r, SCAN_MAX_EXPLICIT, deadExplicit, sweptE); }
    scanHtmlMentions(chunk, (tok) => {
      const r = resolveHtmlPath(tok, worktree);
      if (!r) return;
      const root = matchRoot(r, roots);
      if (root != null && !hasHiddenComponent(r.slice(root.length))) addBounded(sc!.mentioned, r, SCAN_MAX_MENTIONS, deadMention, sweptM);
    });
  }
  const out: string[] = [];
  for (const p of sc.explicit) { try { if (fs.statSync(p).isFile()) out.push(p); } catch {} }
  for (const p of sc.mentioned) {
    if (sc.explicit.has(p)) continue;
    try { const f = fs.statSync(p); if (f.isFile() && f.mtimeMs >= sc.born) out.push(p); } catch {}
  }
  return out;
}

/** All HTML visualizations for a session: convention dir + the html the session itself wrote,
 *  deduped by absolute path. (FIX II: no broad worktree scan — that was repo-wide noise.) */
function vizEntries(vizDir: string, session: any, mentionRoots?: string[]): VizEntry[] {
  const seen = new Set<string>();
  const out: VizEntry[] = [];
  const add = (abs: string) => {
    let real = abs; try { real = fs.realpathSync(abs); } catch {}
    if (seen.has(real)) return; seen.add(real);
    let mtime = 0; try { mtime = fs.statSync(abs).mtimeMs; } catch {}
    out.push({ name: path.basename(abs).replace(/\.html?$/i, ""), file: path.basename(abs), abs, mtime });
  };
  // FIX II: ONLY html RELEVANT to this task — the /visualize convention folder + html the SESSION
  // ITSELF WROTE (from its transcript). NO broad worktree scan (it picked up the shared repo's
  // unrelated html, e.g. leaderboard.html, as noise).
  for (const e of conventionEntries(vizDir, session)) add(e.abs);
  const wt = session?.worktree_path || "";
  for (const p of transcriptHtml(session?.transcript_path || null, wt, [vizDir, ...(mentionRoots || [])])) add(p);
  // NEWEST-FIRST: a task that produced many htmls (e.g. an "investigate training run" session that
  // re-renders a report) should default to the LATEST — so sort by mtime desc (tab 0 = newest, which
  // the renderer selects + auto-surfaces by default), filename localeCompare as a stable tiebreak.
  out.sort((a, b) => (b.mtime - a.mtime) || a.file.localeCompare(b.file));
  return out;
}

/** Public: the session's html files (basename for display). [] when none. */
export function vizFor(vizDir: string, session: any, mentionRoots?: string[]): VizFile[] {
  return vizEntries(vizDir, session, mentionRoots).map((e) => ({ name: e.name, file: e.file, mtime: e.mtime }));
}

/** FIX KK: resolve a requested viz file (by index or basename) to an absolute path. The AUTHORITY
 *  is the session's OWN resolved vizFor list — i.e. the list IS the whitelist. If the requested
 *  index/name is one of the session's listed viz files, serve it (vizFor already vetted it: it
 *  came from the /visualize folder or a Write tool-call the session made, and it exists). There is
 *  NO separate viz_dir/worktree containment re-derivation (that 404'd files the session wrote
 *  OUTSIDE its worktree while the tab still showed them). No traversal risk: we ONLY ever serve a
 *  path vizFor itself produced — never a path built from raw request input. Keeps a realpath +
 *  isFile sanity check. Returns null if not in the list / missing. */
export function resolveVizFile(vizDir: string, session: any, indexOrName: string, mentionRoots?: string[]): string | null {
  const entries = vizEntries(vizDir, session, mentionRoots);
  if (!entries.length) return null;
  let target: VizEntry | undefined;
  if (/^\d+$/.test(indexOrName)) target = entries[parseInt(indexOrName, 10)];
  else target = entries.find((e) => e.file === indexOrName || e.name === indexOrName);
  if (!target) return null; // not in this session's whitelist → 404
  let abs: string; try { abs = fs.realpathSync(target.abs); } catch { return null; }
  try { if (!fs.statSync(abs).isFile()) return null; } catch { return null; }
  return abs;
}
